# Importing this package registers all built-in steps.
from cnequity.steps import (  # noqa: F401
    bars,
    capital,
    commodity,
    events,
    external,
    finalize,
    fundamentals,
    intraday,
    local_assets,
    macro_risk,
    newsboard,
    reference,
    research,
    rotation,
    structure,
    ticks,
    tushare_wide,
)
